version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      #- $(aws ecr get-login --region ap-south-1 --no-include-email)
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 844720368598.dkr.ecr.us-east-1.amazonaws.com
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 844720368598.dkr.ecr.us-west-1.amazonaws.com
      - # Replace with this to your repository URI
      - REPO_EAST=844720368598.dkr.ecr.us-east-1.amazonaws.com/spring-demo-ecr
      - REPO_WEST=844720368598.dkr.ecr.us-west-1.amazonaws.com/spring-demo-ecr
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')      
  build:
    commands:
      - echo Build started on `date`
      - echo building the Jar file
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPO_EAST:latest .
      - docker tag $REPO_EAST:latest $REPO_EAST:$IMAGE_TAG
      - docker tag $REPO_EAST:latest $REPO_WEST:latest
      - docker tag $REPO_EAST:$IMAGE_TAG $REPO_WEST:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      
      # Push to us-east-1
      - echo pushing to repo us-east-1
      - docker push $REPO_EAST:latest
      - docker push $REPO_EAST:$IMAGE_TAG

      # Push to us-west-1
      - echo pushing to repo us-west-1
      - docker push $REPO_WEST:latest
      - docker push $REPO_WEST:$IMAGE_TAG
      
      - echo Writing image definitions file...
      # Give your container name
      - DOCKER_CONTAINER_NAME=spring-demo-ecr

      # Create image definitions for both regions
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPO_EAST:$IMAGE_TAG > imagedefinitions-east.json
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPO_WEST:$IMAGE_TAG > imagedefinitions-west.json

      - echo Printing image definitions...
      - cat imagedefinitions-east.json
      - cat imagedefinitions-west.json
      
artifacts:
  files:
    - imagedefinitions-east.json
    - imagedefinitions-west.json
    - target/springboot-aws-deploy.jar
